//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesSet
    {
        public int Id { get; set; }
        public int IdMagazine { get; set; }
        public int IdBakery { get; set; }
        public double Pieces { get; set; }
        public Nullable<long> SumProfit { get; set; }
    
        public virtual BakerySet BakerySet { get; set; }
        public virtual MagazineSet MagazineSet { get; set; }
    }
}
